const assignments = [
  {
    project: "8 Widmer St, Toronto, Ontario",
    postalCode: "M5V2E7",
    unitNumber: "701",
    details: [
      "Suite Type - 1 + Den",
      "Size (sq.ft.)-569",
      // "Floor Plan-See P.1",
      "Floor - 7/F, Legal Level 6",
      "Locker-No",
      "Parking-No",
      "Occupancy-Now Occupied",
    ],
    op: "$483,500",
    price: "$550,000",
    developerDeposit: "$101,535",
    pricingInformation: [
      "Assignment Price(AP): $550,000",
      "Original Purchase Price: $483,500",
      "Deposit Paid to Developer by Seller: $101,535",
    ],
    sellerProfit: "$66,500",
    deposit: "$80,000",
    remainingBalance: "$88,035",
    imgSrc: "/assignments/1_a.png",
    imgURLs: [
      "/assignments/1_a.png",
      "/assignments/1_b.png",
      "/assignments/1_c.png",
      "/assignments/1_d.png",
      "/assignments/2.png",
    ],
  },
  {
    project: "8188 Yonge St, Thornhill, Ontario",
    postalCode: "L4J 1W5",
    unitNumber: "208",
    details: [
      "Suite Type - 1 + Den, 2 Bath",
      "Size (sq.ft.) - 736",
      // "Floor Plan - See P.1",
      "Floor - 2/F. Legal Level 2",
      "Locker - One Locker included",
      "Parking - One Parking Included",
      "Occupancy - Early 2025",
    ],
    price: "$898000",
    op: "$750400",
    developerDeposit: "$112,580",
    pricingInformation: [
      "Assignment Price(AP): $898000",
      "Price/Sq.ft.: 1221",
      "Original Purchase Price: $750400",
      "Deposit Paid to Developer by Seller: $112580",
    ],
    sellerProfit: "$147,600",
    deposit: "120000",
    remainingBalance: "$140,160",
    imgSrc: "/8188/1.jpeg",
    imgURLs: [
      "/8188/1.jpeg",
      "/8188/2.jpeg",
      "/8188/3.jpeg",
      "/8188/4.jpeg",
      "/8188/5.jpeg",
      "/8188/6.jpeg",
    ],
  },
  {
    project: "252 Church St, Toronto, Ontario",
    postalCode: "M5B 0E6",
    unitNumber: "707",
    details: [
      "Suite Type - Studio",
      "Size (sq.ft.) - 736",
      // "Floor Plan - See P.1",
      "Floor - 7/F. Legal Level 6",
      "Locker - No",
      "Parking - No",
      "Occupancy - Early 2025",
    ],
    developerDeposit: "$107,600",
    price: "$448,000",
    op: "$538,000",
    pricingInformation: [
      "Assignment Price(AP): $448,000",
      "Price/Sq.ft.: $1,530",
      "Original Purchase Price: $538,000",
      "Deposit Paid to Developer by Seller: $107,600",
    ],
    sellerProfit: "-$90000",
    deposit: "$17,600",
    remainingBalance: "$0",
    imgSrc: "/252-church/1.jpeg",
    imgURLs: [
      "/252-church/1.jpeg",
      "/252-church/2.jpeg",
      "/252-church/3.jpeg",
      "/252-church/4.jpeg",
    ],
  },
  {
    project: "UC Tower 2, Oshawa, Ontario",
    postalCode: " L1L 0G4",
    unitNumber: "1109",
    details: [
      "Suite Type - Studio | 1 Bath",
      "Size (sq.ft.) - 455",
      // "Floor Plan - See P.1",
      "Floor - 11/F",
      "Locker - No",
      "Parking - Yes",
      "Occupancy - November, 2024",
    ],
    price: "$445,200",
    op: "$422,540",
    developerDeposit: "$82,531",
    pricingInformation: [
      "Assignment Price(AP): $445,200",
      "Price/Sq.ft.: $979",
      "Original Purchase Price: $422,540",
      "Deposit Paid to Developer by Seller: $82,531",
    ],
    sellerProfit: "$22660",
    deposit: "$82,531",
    remainingBalance: "$22,660",
    imgSrc: "/uc2/1.jpeg",
    imgURLs: [
      "/uc2/1.jpeg",
      "/uc2/2.jpeg",
      "/uc2/3.jpeg",
      "/uc2/4.jpeg",
      "/uc2/5.jpeg",
    ],
  },
];

export default assignments;
