// data.ts
export const scheduleData = [
  {
    id: 1,
    title: "Pre-construction with Dan Wong",
    subtitle: "An unparalleled investment experience.",
    duration: "60 Min",
    link: "/schedule/time?id=1&recepient=dan%20wong",
    calendarId: process.env.NEXT_PUBLIC_REACT_APP_CALENDAR_ID_1,
    accessToken: process.env.NEXT_PUBLIC_REACT_APP_GOOGLE_ACCESS_TOKEN_1,
    apiKey: process.env.NEXT_PUBLIC_REACT_APP_GOOGLE_API_KEY_1,
  },
  {
    id: 2,
    title: "Resale / Assignment with Michael Ho",
    subtitle: "An unparalleled investment experience.",
    duration: "60 Min",
    link: "/schedule/time?id=2&recepient=michael%20ho",
    calendarId: process.env.NEXT_PUBLIC_REACT_APP_CALENDAR_ID_2,
    accessToken: process.env.NEXT_PUBLIC_REACT_APP_GOOGLE_ACCESS_TOKEN_2,
    apiKey: process.env.NEXT_PUBLIC_REACT_APP_GOOGLE_API_KEY_2,
  },
  {
    id: 3,
    title: "Rental Listing with Carl Chen",
    subtitle: "An unparalleled investment experience.",
    duration: "30 Min",
    link: "/schedule/time?id=3&recepient=carl%20chen",
    calendarId: process.env.NEXT_PUBLIC_REACT_APP_CALENDAR_ID_3,
    accessToken: process.env.NEXT_PUBLIC_REACT_APP_GOOGLE_ACCESS_TOKEN_3,
    apiKey: process.env.NEXT_PUBLIC_REACT_APP_GOOGLE_API_KEY_3,
  },
  {
    id: 4,
    title: "Rental Management with Vivian Tran",
    subtitle: "An unparalleled investment experience.",
    duration: "30 Min",
    link: "/schedule/time?id=4&recepient=vivian%20tran",
    calendarId: process.env.NEXT_PUBLIC_REACT_APP_CALENDAR_ID_4,
    accessToken: process.env.NEXT_PUBLIC_REACT_APP_GOOGLE_ACCESS_TOKEN_4,
    apiKey: process.env.NEXT_PUBLIC_REACT_APP_GOOGLE_API_KEY_4,
  },
];
