/* import MarketNewsNavbar from "../../components/market-news-navbar"; */

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <div className=" bg-[#000]">
      {/* <MarketNewsNavbar /> */}
      <div className="mx-16">{children}</div>
    </div>
  );
}
